project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
  resources:
    - "images"
    - "data/**"
    - "assets/**"
    - "theme-ecowitt.css"

website:
  page-navigation: true
  bread-crumbs: false
  site-url: https://gisma.github.io/mikrotik-burgwald
  title: "Hydro-Messnetz Burgwald"
  search:
    location: sidebar
    type: textbox
  navbar:
    logo: images/logo1.png
    right:
      - text: "Impressum"
        href: impressum.qmd
  sidebar:
    pinned: true
    align: center
    style: "docked"
    collapse-level: 1
    contents:
      - section: "Über..."
        contents:
          - index.qmd
      - section: "Daten-Interface"
        contents:
          # - text: "Daten Repository"
          #   href: index_data.qmd
          - text: "Status Informationen"
            href: debug-data.qmd
          - text: "Dashboard"
            href: live-data.qmd
          - text: "Dashboard Doku"
            href: dashboard_doku_de.qmd          
      - section: "Setup Doku"
        contents:
          - text: "Hub & TNN"
            href: lorawan_doku.qmd
          - text: "Dragino Sensoren"
            href: lorawan_dragino.qmd


format:
  html:
    theme:
      light: lumen
      dark: [lumen, css/theme-dark.scss]
    code-background: true
    code-copy: true
    css: css/styles.css      # ← sicherstellen, dass dein CSS lädt
    toc: true
    link-external-icon: false
    link-external-newwindow: true
    link-external-filter: '^(?:https?:)\/\/(www\.quarto\.org|gisma\.github\.io)\/'
    code-overflow: wrap
    highlight-style: github

execute:
  freeze: false
  cache: false

diagram:
  mermaid:
    engine: kroki
    kroki-url: https://kroki.io
