# _quarto.yml — Website mit Sidebar-Navigation

project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - data/index.qmd
    - lorawan_doku.qmd
    - live-data.qmd
  resources:
    - "data/**"             # kopiert alle Dateien in data/ mit ins Output


website:
  site-url: https://gisma.github.io/mikrotik-burgwald
  title: "Hydro-Messnetz Burgwald"
  search:
    location: sidebar     # Suchfeld in der Sidebar
    type: textbox
  navbar:                 # optional ganz weglassen, wenn Sidebar reicht
    left:
      - text: "Home"
        href: index.qmd
  sidebar:
    pinned: true          # Sidebar ist permanent sichtbar
    align: center
    style: "docked"       # "docked" (links) oder "floating"
    collapse-level: 1     # ab Ebene 2 einklappen
    contents:
      - section: "Über..."
        contents:
          - index.qmd
      - section: "LoRaWAN"
        contents:
          - text: "Anleitung"
            href: lorawan_doku.qmd
      - section: "Daten Vorschau"
        contents:
          - text: "Live Daten"
            href: live-data.html  
          - text: "Daten Repository"
            href: data/

format:
  html:
    theme:
      light: lumen
      dark: [lumen, css/theme-dark.scss]
    code-background: true
    code-copy: true
    css: css/styles.css
    toc: true
    link-external-icon: true
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/www\.quarto\.org\/custom'
    code-overflow: wrap
    highlight-style: github

execute:
  freeze: false
  cache: false

diagram:
  mermaid:
    engine: kroki
    kroki-url: https://kroki.io

