name: Build & Publish Quarto (R/knitr)

on:
  push:
    branches: [ main ]        # ggf. deinen Default-Branch eintragen
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Quarto installieren
      - uses: quarto-dev/quarto-actions/setup@v2

      # R bereitstellen (für knitr)
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'stable'

      # (optional) R-Pakete installieren – knitr ist meist da, hier nur Sicherheit
      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("knitr"), repos="https://cloud.r-project.org")'

      # Rendern
      - name: Quarto render
        run: |
          QUARTO_PRINT_STACKTRACE=1 quarto render

      # Nach /docs veröffentlichen (Pages-Ordner)
      - name: Publish to docs/
        run: |
          rm -rf docs
          mkdir -p docs
          cp -r _site/* docs/

      # Commit der gerenderten Website
      - name: Commit rendered site
        run: |
          git config user.name  "quarto-bot"
          git config user.email "quarto-bot@example.com"
          git add docs
          git commit -m "Publish rendered site" || echo "no changes"
          git push
