name: Build & Publish Quarto (R/knitr)

on:
  push:
    branches: [ main ]   # ggf. anpassen
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04   # <— NICHT 24.04

    steps:
      - uses: actions/checkout@v4

      - uses: quarto-dev/quarto-actions/setup@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'          # alternativ: '4.4.1'
          use-public-rspm: true

      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("knitr","rmarkdown"), repos="https://cloud.r-project.org")'

      - name: Render site
        run: |
          quarto render

      - name: Publish to docs/
        run: |
          rm -rf docs && mkdir -p docs
          cp -r _site/* docs/

      - name: Commit rendered site
        run: |
          git config user.name  "quarto-bot"
          git config user.email "quarto-bot@example.com"
          git add docs
          git commit -m "Publish rendered site" || true
          git push
