name: Build & Publish Quarto (R/knitr)

on:
  push:
    branches: ['**']
    paths:
      - '**.qmd'
      - '_quarto.yml'
      - 'data/**'
      - '.github/workflows/quarto-render.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: quarto-dev/quarto-actions/setup@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          use-public-rspm: true
      - name: Install R packages
        run: Rscript -e 'install.packages(c("knitr","rmarkdown"), repos="https://cloud.r-project.org")'
      - name: Render site (to docs/)
        run: quarto render
      - name: Commit rendered site
        run: |
          git config user.name  "quarto-bot"
          git config user.email "quarto-bot@example.com"
          git add docs
          git commit -m "Publish rendered site" || echo "no changes"
          git push
