name: Quarto Render

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 * * * *"   # optional: st체ndlich rendern
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # --- Python vorbereiten & Daten ziehen ---
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas plotly pyarrow

      - name: Python Daten-Seite erzeugen
        env:
          TTN_APP_ID:   ${{ secrets.TTN_APP_ID }}
          TTN_REGION:   ${{ secrets.TTN_REGION }}
          TTN_API_KEY:  ${{ secrets.TTN_API_KEY }}
          DEVICES:      ${{ secrets.DEVICES }}
        run: |
          mkdir -p data
          python scripts/pull_all_devices.py

      - name: Ensure placeholder if missing
        run: |
          mkdir -p data
          if [ ! -f data/data.html ]; then
            echo '<!doctype html><meta charset="utf-8"><p>(Noch keine Daten verf체gbar. Die TTN-Pipeline erzeugt diese Seite beim n채chsten Lauf.)</p>' > data/data.html
          fi

      # --- Quarto vorbereiten ---
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Setup R (f체r knitr/includeHTML)
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          use-public-rspm: true

      - name: Install R packages
        run: Rscript -e 'install.packages(c("knitr","rmarkdown","htmltools"), repos="https://cloud.r-project.org")'

      # --- Render ---
      - name: Quarto render
        run: quarto render --no-cache

      # --- Deploy zu gh-pages (docs/) ---
      - name: Commit rendered site
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/ data/
          git commit -m "Quarto render $(date -u +%Y-%m-%dT%H:%M:%SZ)" || echo "no changes"
          git push
